### ISSUE TITLE
IndexError: index out of range

### ISSUE THREAD

**Issue by Woersty** [sarnau/Inside-The-Loxone-Miniserver#19]
```

root@loxberrydev:/opt/loxberry# python3 LoxoneMonitorServer.py
Starting Monitor Server Proxy...
Starting Monitor Server Logger...
2020-04-18 12:25:52.770 PRG cycle duration 1655us 50cycles/s Contextswitches:0 Contextswitches from Int:0 (250715624/21319317) IO time:261us
2020-04-18 12:25:52.970 HTTPCL: Add Command from Wetterstation
2020-04-18 12:25:53.034 PRG send special state event BetriebszeitzÃ¤hler KWL Filter aktuell+gesamt 0d92bb4f-00c7-bffc-ffffeee000000000 0d92bb4f-00c7-bff1-ffffd18721cf449b 1
2020-04-18 12:25:53.036 PRG send special state event Poolwasser  (Nutzungsdauer) 0c94b791-031f-52f9-ffffeee000000000 0d5b677f-0206-a71c-ffffeee000000000 1
2020-04-18 12:25:53.512 HTC Connect to Host wetterstation.woersty.com, Port: 80
2020-04-18 12:25:54.034 PRG send special state event BetriebszeitzÃ¤hler KWL Filter aktuell+gesamt 0d92bb4f-00c7-bffc-ffffeee000000000 0d92bb4f-00c7-bff1-ffffd18721cf449b 1
2020-04-18 12:25:54.036 PRG send special state event Poolwasser  (Nutzungsdauer) 0c94b791-031f-52f9-ffffeee000000000 0d5b677f-0206-a71c-ffffeee000000000 1
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "LoxoneMonitorServer.py", line 195, in monitorserver_logger
    data = parsePackage(data)
  File "LoxoneMonitorServer.py", line 180, in parsePackage
    parsePackageContent(pkg)
  File "LoxoneMonitorServer.py", line 162, in parsePackageContent
    parsePackageLogging(pkg,strType,parameterCount)
  File "LoxoneMonitorServer.py", line 108, in parsePackageLogging
    while pkg[offset]:
IndexError: index out of range

^C2020-04-18 12:25:54.072 Traceback (most recent call last):
  File "LoxoneMonitorServer.py", line 231, in <module>
    x.join()
  File "/usr/lib/python3.7/threading.py", line 1032, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.7/threading.py", line 1048, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt

```

**Comment by sarnau** [comment]
Hmm, neues Packet, das der Script nicht kennt? Ich habe es nicht mit der neusten Version ausprobiert.
